# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBNk9O5bOHD2mq9QpL7JQhxH5n5BRTku
"""



#Guessing a letter in the inserted word

word = input('Insert a word: ')
letter = int(input('Wich letter do you want me to discover? '))
word[letter]